Repository SilSo-communityFromFailToOvercome/silso_dev_toyproject, pull requests merged in 2025-07, with the labels that each got.

#1 docs - add-developers-house-rules!
  README.md
  README_KOR.md
Labels: documentation

#2 feat: added game_detail file
  GAME_DETAIL.md
Labels: enhancement, features

#3 feat/add_toy_project_skeleton_code(except_database)
  README.md
  READMEKOR_TOYPROJECT.md
  README_KOR.md
  README_TOYPROJECT.md
  assets/images/egg_state0.png
  assets/images/egg_state1.png
  assets/images/egg_state2.png
  assets/images/egg_state3.png
  lib/main.dart
  lib/models/pet.dart
  lib/models/reflection.dart
  lib/providers/pet_notifier.dart
  lib/screens/clean_page.dart
  lib/screens/feed_page.dart
  lib/screens/history_page.dart
  lib/screens/my_page.dart
  lib/screens/play_page.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: good first issue, help wanted, features

#6 style/toyproject-layout-modify-mypage(detail page UI modify)
  lib/screens/clean_page.dart
  lib/screens/feed_page.dart
  lib/screens/history_page.dart
  lib/screens/play_page.dart
Labels: modify

#8 feat/animation_effect(after finish; clean/play/feed animate effect)
  ANIMATION_SYSTEM.md
  lib/models/pet.dart
  lib/providers/pet_notifier.dart
  lib/screens/my_page.dart
  lib/widgets/pet_task_animation_widget.dart
Labels: enhancement, features

#11 feat: Add complete community feature with navigation integration
  lib/models/comment.dart
  lib/models/community.dart
  lib/models/community_membership.dart
  lib/models/post.dart
  lib/providers/community_providers.dart
  lib/screens/community_detail_page.dart
  lib/screens/community_page.dart
  lib/screens/my_page.dart
  lib/services/comment_service.dart
  lib/services/community_service.dart
  lib/services/post_service.dart
  lib/widgets/create_post_dialog.dart
  lib/widgets/report_dialog.dart
Labels: features

#12 Modify/fix layout featuers
  lib/screens/community_page.dart
  lib/widgets/create_post_dialog.dart
Labels: enhancement, modify

#14 Docs/code review material
  docs/DATA_MODELS_DOCUMENTATION.md
  docs/SERVICES_DOCUMENTATION.md
  docs/UI_ARCHITECTURE_DOCUMENTATION.md
  docs/animation/ANIMATION_SYSTEM.md
  docs/animation/CLEAN_BUTTON_ANIMATION_DOCUMENTATION.md
  docs/game/GAME_DETAIL.md
  docs/project_goal/READMEKOR_TOYPROJECT.md
  docs/project_goal/README_TOYPROJECT.md
  docs/rules/README.md
  docs/rules/README_KOR.md
  docs/study/CODE_REVIEW_STUDY_GUIDE.md
  docs/study/COMPLETE_CODE_REVIEW_PACKAGE.md
  docs/study/UPGRADED_DOCUMENTATION_SUMMARY.md
Labels: documentation
